{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plex.fullname" . }}-config
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | default "20Gi" }}
---
{{- end }}

{{- if and .Values.persistence.transcode.enabled (not .Values.persistence.transcode.existingClaim) (not .Values.persistence.transcode.emptyDir.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plex.fullname" . }}-transcode
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.transcode.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.persistence.transcode.storageClass }}
  storageClassName: {{ .Values.persistence.transcode.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.transcode.size | default "20Gi" }}
---
{{- end }}

{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plex.fullname" . }}-media
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.persistence.media.storageClass }}
  storageClassName: {{ .Values.persistence.media.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | default "200Gi" }}
{{- end }}